spring.application.name=ts-user
spring.application.description = Task Scheduler - User module

server.forward-headers-strategy = framework

management.endpoints.web.exposure.include=health
management.endpoint.health.probes.enabled=true

ts.jwt.secret=${TS_JWT_SECRET}
ts.jwt.expiration=${TS_JWT_EXPIRATION}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=${TS_SHOW_SQL}

spring.datasource.url=jdbc:postgresql://${TS_POSTGRES_HOST}:${TS_POSTGRES_PORT}/${TS_POSTGRES_DB}
spring.datasource.username=${TS_POSTGRES_USER}
spring.datasource.password=${TS_POSTGRES_PASSWORD}

viacep.url=https://viacep.com.br
